In [1]:
import pandas as pd
import numpy as np
df=pd.read_excel('/Users/ayushjoshi/Downloads/Take Home Assignment Dataset ppython.xlsx')
df.head()

,Route Number,Date of Extraction,Departure Date,SRP Rank,Operator,Bus Type,Is AC,Is Seater,Is Sleeper,Departure Time,...,BP Count,DP Count,Total Ratings,Number of Reviews,Bus Score,Is Seat Layout Available,Is Live Tracking Available,Is M-Ticket Enabled,Group Key,Departure Time (Num)
0,Route 1,"16 Mar 2026, 09:34:45",2026-03-16,1/165,Operator 1,Electric A/C Seater (2+2),1.0,1.0,NaN,17:50:00,...,12,14,4.6,459.0,3.71,True,1.0,True,Route 1|16-03-2026|TRUE|NA,0.743056
1,Route 1,"16 Mar 2026, 09:34:45",2026-03-16,2/165,Operator 2,Bharat Benz A/C Sleeper (2+1),1.0,NaN,1.0,22:00:00,...,13,20,4.9,408.0,4.48,True,1.0,True,Route 1|16-03-2026|TRUE|TRUE,0.916667
2,Route 1,"16 Mar 2026, 09:34:45",2026-03-16,3/165,Operator 3,Bharat Benz A/C Sleeper (2+1),1.0,NaN,1.0,22:15:00,...,12,30,4.8,173.0,3.77,True,1.0,True,Route 1|16-03-2026|TRUE|TRUE,0.927083
3,Route 1,"16 Mar 2026, 09:34:45",2026-03-16,4/165,Operator 3,A/C Sleeper (2+1),1.0,NaN,1.0,23:15:00,...,31,28,4.6,781.0,3.91,True,1.0,True,Route 1|16-03-2026|TRUE|TRUE,0.968750
4,Route 1,"16 Mar 2026, 09:34:45",2026-03-16,5/165,Operator 4,Bharat Benz A/C Sleeper (2+1),1.0,NaN,1.0,23:40:00,...,12,23,4.7,320.0,3.80,True,1.0,True,Route 1|16-03-2026|TRUE|TRUE,0.986111

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 862388 entries, 0 to 862387
Data columns (total 34 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Route Number                862388 non-null  object
 1   Date of Extraction          862388 non-null  object
 2   Departure Date              862388 non-null  datetime64[ns]
 3   SRP Rank                    862388 non-null  object
 4   Operator                    862388 non-null  object
 5   Bus Type                    862388 non-null  object
 6   Is AC                       783656 non-null  float64
 7   Is Seater                   404276 non-null  float64
 8   Is Sleeper                  746178 non-null  float64
 9   Departure Time              862388 non-null  object
 10  Arrival Time                862388 non-null  object
 11  Journey Duration (Min)      862388 non-null  int64
 12  DOJ                         862388 non-null  datetime64[ns]
 13  Fare List                   862388 non-null  object
 14  Discounted Prices           273302 non-null  object
 15  Weighted Average Price      861633 non-null  float64
 16  Seat Prices                 860881 non-null  object
 17  Available Seats             862388 non-null  int64
 18  Total Seats                 862388 non-null  int64
 19  Available Window Seats      841170 non-null  float64
 20  Available Single Seats      716090 non-null  float64
 21  Available Aisle Seats       841497 non-null  float64
 22  Available Upper Seats       727920 non-null  float64
 23  Available Lower Seats       860976 non-null  float64
 24  BP Count                    862388 non-null  int64
 25  DP Count                    862388 non-null  int64
 26  Total Ratings               862388 non-null  float64
 27  Number of Reviews           849728 non-null  float64
 28  Bus Score                   855675 non-null  float64
 29  Is Seat Layout Available    862388 non-null  bool
 30  Is Live Tracking Available  622666 non-null  float64
 31  Is M-Ticket Enabled         862388 non-null  bool
 32  Group Key                   862388 non-null  object
 33  Departure Time (Num)        862388 non-null  float64
dtypes: bool(2), datetime64[ns](2), float64(14), int64(5), object(11)
memory usage: 212.2+ MB

In [3]:
def calculate_group_median(group):
    times = group['Departure Time (Num)'].values
    prices = group['Weighted Average Price'].values
    medians = []
    for t in times:
        mask = np.abs(times - t) <= 2/24
        medians.append(np.median(prices[mask]))
    group['Median Price (Similar Buses)'] = medians
    return group

df = df.groupby('Group Key', group_keys=False).apply(calculate_group_median)
print("Done!")
print(df[['Operator', 'Weighted Average Price', 'Median Price (Similar Buses)']].head(10))

Done!
     Operator  Weighted Average Price  Median Price (Similar Buses)
0  Operator 1                  374.82                        646.64
1  Operator 2                  818.07                        967.91
2  Operator 3                  734.26                        967.91
3  Operator 3                  838.62                        967.91
4  Operator 4                  829.04                        969.21
5  Operator 2                  853.75                        967.91
6  Operator 5                 1004.00                        967.91
7  Operator 6                  575.86                        967.91
8  Operator 7                  540.92                        967.91
9  Operator 8                  967.75                        967.91

/var/folders/7v/f25sz_fn4298sw0_wb7s9mk40000gn/T/ipykernel_5859/1276851014.py:11: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby('Group Key', group_keys=False).apply(calculate_group_median)

In [8]:
df.head()

,Route Number,Date of Extraction,Departure Date,SRP Rank,Operator,Bus Type,Is AC,Is Seater,Is Sleeper,Departure Time,...,Bus Score,Is Seat Layout Available,Is Live Tracking Available,Is M-Ticket Enabled,Group Key,Departure Time (Num),Median Price (Similar Buses),% Difference,Price Flag,Price Difference (Rs)
0,Route 1,"16 Mar 2026, 09:34:45",2026-03-16,1/165,Operator 1,Electric A/C Seater (2+2),1.0,1.0,NaN,17:50:00,...,3.71,True,1.0,True,Route 1|16-03-2026|TRUE|NA,0.743056,646.64,-0.420358,,-271.82
1,Route 1,"16 Mar 2026, 09:34:45",2026-03-16,2/165,Operator 2,Bharat Benz A/C Sleeper (2+1),1.0,NaN,1.0,22:00:00,...,4.48,True,1.0,True,Route 1|16-03-2026|TRUE|TRUE,0.916667,967.91,-0.154808,,-149.84
2,Route 1,"16 Mar 2026, 09:34:45",2026-03-16,3/165,Operator 3,Bharat Benz A/C Sleeper (2+1),1.0,NaN,1.0,22:15:00,...,3.77,True,1.0,True,Route 1|16-03-2026|TRUE|TRUE,0.927083,967.91,-0.241396,,-233.65
3,Route 1,"16 Mar 2026, 09:34:45",2026-03-16,4/165,Operator 3,A/C Sleeper (2+1),1.0,NaN,1.0,23:15:00,...,3.91,True,1.0,True,Route 1|16-03-2026|TRUE|TRUE,0.968750,967.91,-0.133576,,-129.29
4,Route 1,"16 Mar 2026, 09:34:45",2026-03-16,5/165,Operator 4,Bharat Benz A/C Sleeper (2+1),1.0,NaN,1.0,23:40:00,...,3.80,True,1.0,True,Route 1|16-03-2026|TRUE|TRUE,0.986111,969.21,-0.144623,,-140.17

In [9]:
print(df['Operator'].unique())

['Operator 1' 'Operator 2' 'Operator 3' ... 'Operator 1325'
 'Operator 1326' 'Operator 1327']

In [10]:
print(df[df['Operator'].str.contains('Flix', case=False, na=False)]['Operator'].unique())

['Flixbus']

In [11]:
# % Difference
df['% Difference'] = (df['Weighted Average Price'] - df['Median Price (Similar Buses)']) / df['Median Price (Similar Buses)']

# Price Flag
def flag(row):
    if row['Operator'] != 'Flixbus':
        return ''
    if row['Median Price (Similar Buses)'] == 0:
        return 'No Comparable Buses'
    elif row['% Difference'] > 0.2:
        return 'Too High'
    elif row['% Difference'] < -0.2:
        return 'Too Low'
    else:
        return 'OK'

df['Price Flag'] = df.apply(flag, axis=1)

# Price Difference
df['Price Difference (Rs)'] = df['Weighted Average Price'] - df['Median Price (Similar Buses)']

print("Done!")
print(df[df['Operator']=='Flixbus'][['Operator','Weighted Average Price','Median Price (Similar Buses)','% Difference','Price Flag','Price Difference (Rs)']].head(10))

Done!
    Operator  Weighted Average Price  Median Price (Similar Buses)  \
16   Flixbus                  795.39                       967.910
43   Flixbus                  712.22                       967.910
44   Flixbus                  700.63                       967.910
82   Flixbus                  720.43                       967.910
95   Flixbus                  711.60                       967.910
106  Flixbus                  648.16                       944.435
118  Flixbus                  613.96                       967.910
127  Flixbus                  704.02                       876.150
133  Flixbus                  682.11                       945.000
150  Flixbus                  622.27                       967.910

     % Difference Price Flag  Price Difference (Rs)
16      -0.178240         OK               -172.520
43      -0.264167    Too Low               -255.690
44      -0.276141    Too Low               -267.280
82      -0.255685    Too Low               -247.480
95      -0.264808    Too Low               -256.310
106     -0.313706    Too Low               -296.275
118     -0.365685    Too Low               -353.950
127     -0.196462         OK               -172.130
133     -0.278190    Too Low               -262.890
150     -0.357099    Too Low               -345.640

In [12]:
# Filter only Flixbus rows for output
flixbus_output = df[df['Operator'] == 'Flixbus'][[
    'Route Number', 'Departure Date', 'Operator', 'Bus Type',
    'Is AC', 'Is Seater', 'Is Sleeper', 'Departure Time',
    'Weighted Average Price', 'Median Price (Similar Buses)',
    '% Difference', 'Price Flag', 'Price Difference (Rs)'
]]

# Export to Excel
flixbus_output.to_excel('/Users/ayushjoshi/Downloads/Flixbus_Price_Flagging.xlsx', 
                         sheet_name='Flagging Output', index=False)

print("Done! File saved!")
print(f"Total Flixbus rows: {len(flixbus_output)}")
print(f"Too High: {(flixbus_output['Price Flag']=='Too High').sum()}")
print(f"Too Low: {(flixbus_output['Price Flag']=='Too Low').sum()}")
print(f"OK: {(flixbus_output['Price Flag']=='OK').sum()}")

Done! File saved!
Total Flixbus rows: 31110
Too High: 4087
Too Low: 12664
OK: 14359

In [13]:
print(df['Operator'].value_counts()['Flixbus'])

31110

<class 'pandas.core.frame.DataFrame'>
Index: 862388 entries, 0 to 862387
Data columns (total 38 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Route Number                  862388 non-null  object
 1   Date of Extraction            862388 non-null  object
 2   Departure Date                862388 non-null  datetime64[ns]
 3   SRP Rank                      862388 non-null  object
 4   Operator                      862388 non-null  object
 5   Bus Type                      862388 non-null  object
 6   Is AC                         783656 non-null  float64
 7   Is Seater                     404276 non-null  float64
 8   Is Sleeper                    746178 non-null  float64
 9   Departure Time                862388 non-null  object
 10  Arrival Time                  862388 non-null  object
 11  Journey Duration (Min)        862388 non-null  int64
 12  DOJ                           862388 non-null  datetime64[ns]
 13  Fare List                     862388 non-null  object
 14  Discounted Prices             273302 non-null  object
 15  Weighted Average Price        861633 non-null  float64
 16  Seat Prices                   860881 non-null  object
 17  Available Seats               862388 non-null  int64
 18  Total Seats                   862388 non-null  int64
 19  Available Window Seats        841170 non-null  float64
 20  Available Single Seats        716090 non-null  float64
 21  Available Aisle Seats         841497 non-null  float64
 22  Available Upper Seats         727920 non-null  float64
 23  Available Lower Seats         860976 non-null  float64
 24  BP Count                      862388 non-null  int64
 25  DP Count                      862388 non-null  int64
 26  Total Ratings                 862388 non-null  float64
 27  Number of Reviews             849728 non-null  float64
 28  Bus Score                     855675 non-null  float64
 29  Is Seat Layout Available      862388 non-null  bool
 30  Is Live Tracking Available    622666 non-null  float64
 31  Is M-Ticket Enabled           862388 non-null  bool
 32  Group Key                     862388 non-null  object
 33  Departure Time (Num)          862388 non-null  float64
 34  Median Price (Similar Buses)  861486 non-null  float64
 35  % Difference                  861486 non-null  float64
 36  Price Flag                    862388 non-null  object
 37  Price Difference (Rs)         861486 non-null  float64
dtypes: bool(2), datetime64[ns](2), float64(17), int64(5), object(12)
memory usage: 277.3+ MB